apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-list.configmap.name" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
data:
  # Backend Config
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ include "todo-list.database.fullname" . }}:{{ .Values.database.service.port }}/{{ .Values.database.auth.database }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.auth.username | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.env.corsAllowedOrigins | quote }}
  JWT_expirationMs: {{ .Values.backend.env.jwtExpirationMs | quote }}
  # Frontend Config
  VITE_API_URL: {{ .Values.frontend.env.apiUrl | quote }}
  # DB Config
  MYSQL_DATABASE: {{ .Values.database.auth.database | quote }}
