{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-list.database.fullname" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-list.database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "todo-list.database.selectorLabels" . | indent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.database.service.targetPort }}
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-list.secret.name" . }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-list.configmap.name" . }}
                  key: MYSQL_DATABASE
          {{- if .Values.database.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -p{{ .Values.database.auth.rootPassword }}
            initialDelaySeconds: {{ .Values.database.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.database.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.database.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.database.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.database.persistence.enabled }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          {{- end }}
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.database.persistence.enabled }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "todo-list.pvc.name" . }}
      {{- end }}
      {{- with .Values.database.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
